version: "3.1"
services:

    bd:
      image: mysql:8.0
      container_name: bd
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=laradock
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8005:3306"

    webserver:
      image: nginx:alpine
      container_name: laradock-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8088:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: laradock-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini